name: revivals
description: "A new Flutter project."
publish_to: 'none'
version: 7.0.0+6

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  country_code_picker: ^3.0.0
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  pluralize: ^0.0.8
  mailer: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_signin_button: ^2.0.0
  app_tracking_transparency: ^2.0.6
  flutter_spinkit: ^5.2.1
  auto_size_text: ^3.0.0
  intl_phone_field: ^3.2.0
  basic_utils: ^5.7.0
  accordion: ^2.6.0
  country_picker: ^2.0.26
  country_flags: ^3.0.0
  country_icons: ^3.0.0
  flutter_switch: ^0.3.2
  flutter_inset_box_shadow: ^1.0.8
  badges: ^3.1.2
  password_strength_checker: ^1.2.4
  dropdown_button2: ^2.3.9
  booking_calendar: ^1.1.10
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  numpad_layout: ^0.0.3
  rename_app: ^1.6.1
  syncfusion_flutter_charts: ^27.2.5
  animated_digit: ^3.2.3
  flutter_native_splash: ^2.4.1
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  syncfusion_flutter_datepicker: ^27.2.5
  image_cropper: ^9.1.0
  http: ^1.4.0
  flutter_stripe: ^11.5.0
  cloud_functions: ^5.5.2
  flutter_dotenv: ^5.2.1
  # dio: ^5.8.0+1
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0
  curved_navigation_bar: ^1.0.6
  # device_preview: ^1.2.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  intl: ^0.19.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/new_velaa_logo_transparent.png"

flutter:
  uses-material-design: true

  fonts:
      - family: Lovelo
        fonts:
          - asset: assets/fonts/lovelo_black.otf
          # - asset: assets/fonts/league_spartan.otf
          # - asset: assets/fonts/quicksand.otf

  assets:
      - assets/login/
      - assets/logos/
      - assets/img/items/
      - assets/img/backgrounds/
      - assets/img/icons/
      - assets/img/icons/
      - .env

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: assets/logos/new_velaa_icon_1024.png
  
  android_12: 
    color: "#ffffff"
    image: assets/logos/new_velaa_icon_1024.png
    
  # ios_content_mode: center